services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    profiles:
      - production
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    networks:
      - rabbitmq_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - .env
    networks:
      - rabbitmq_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '5672:5672'
      - '15672:15672'
  news_consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: news_base
    profiles:
      - consumers
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  rss_atom_consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: rss_atom_base
    profiles:
      - consumers
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
  searcher_consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: searcher_base
    profiles:
      - consumers
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
      target: ollama_base
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rabbitmq_network
volumes:
  ollama_data:
    name: ollama_data

networks:
  rabbitmq_network:
    driver: bridge